### ISSUE TITLE
V1.0.22webdavBUG

### ISSUE THREAD

**Issue by 676407926** [Tiarait/HTTP-FS-file-server#1] opened 2023-12-12 07:29 UTC
Webdav service, web access garbled, client normal.
[<img src="https://github.com/Tiarait/HTTP-FS-file-server/assets/100478073/211a78d5-8339-4cf8-b38e-5e15b4472402" align="left" alt="client"
width="200" hspace="10" vspace="10">](https://github.com/Tiarait/HTTP-FS-file-server/assets/100478073/211a78d5-8339-4cf8-b38e-5e15b4472402) 
[<img src="https://github.com/Tiarait/HTTP-FS-file-server/assets/100478073/4f9e7b28-21e0-4268-8930-69f4d6ce3134" align="left" alt="web"
width="200" hspace="10" vspace="10">](https://github.com/Tiarait/HTTP-FS-file-server/assets/100478073/4f9e7b28-21e0-4268-8930-69f4d6ce3134)

**Comment by Tiarait** [comment] 2023-12-20 16:41
Fixed webdav api for windows in [version 1.0.23](https://github.com/Tiarait/HTTP-FS-file-server/blob/main/Changelog.md#1023)
 Let's wait until the version appears in Google Play, **if the problem is still** - give me a link or name your client

**Comment by 676407926** [comment] 2023-12-21 09:24
Hello, end test, v1.0.23, the problem of garbled code during web access remains the same. I use Xiaomi 6 Android 9.0. The feedback video has been synchronized to "V1.0.23.ipv6.doesn't work".

**Comment by Tiarait** [comment] 2023-12-21 11:51
I close it. Please follow the discussion in #3 .

**Closed by Tiarait** 2023-12-21 11:51 UTC
Labels: bug, good first issue
